Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
  - 'Ruby Basics Part 4/*'
  - 'Ruby Basics Part 6/*'

Layout/LineLength:
  Max: 120
  IgnoredPatterns: ['(\A|\s)#']

Metrics/AbcSize:
  Max: 35

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/ParameterLists:
  Max: 6

Metrics/CyclomaticComplexity:
  Max: 7

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
